version: "3.9"
services:
  blue-centos7-systemd-sshd:
    cap_add:
    - SYS_ADMIN
    environment:
    - container=docker
    build: /dockerfile/blue-centos7-systemd-sshd
    ports:
      - "20022:22"
    privileged: false
    tmpfs:
    - /run
    - /run/lock
    - /tmp
    volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"