version: "3.9"
services:
  blue-centos7-systemd-sshd:
    build: /dockerfile/blue-centos7-systemd-sshd
    ports:
      - "20022:22"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup"

  blue-centos7-systemd-docker:
    build: /dockerfile/blue-centos7-systemd-docker
    ports:
      - "20022:22"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"